name: books-service
namespace: dev

replicaCount: 1

image:
  repository: khawlarouiss/ci-cd-books
  tag: ""

service:
  port: 80
  targetPort: 8081

config:
  LOG_LEVEL: INFO

ingress:
  enabled: false