name: books-service
namespace: prod

replicaCount: 1

image:
  repository: khawlarouiss/ci-cd-books
  tag: latest

service:
  port: 80
  targetPort: 8081

config:
  LOG_LEVEL: INFO

ingress:
  enabled: false