name: bookstore-frontend
namespace: prod

replicaCount: 1

image:
  repository: khawlarouiss/ci-cd-bookstore-frontend
  tag: latest

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: prod.bookstore.com
  tlsSecret: bookstore-prod-tls
