include:
  - project: 'rouis.khawla09/gitlab-shared-template'
    ref: main
    file: '/pipeline.yml'

variables:
  SERVICE_NAME: api-gateway
  SERVICE_DIR: services/api-gateway
  SERVICE_TYPE: backend
  DOCKER_IMAGE: khawlarouiss/ci-cd-gateway

stages:
  - build
  - docker
  - deploy-staging
  - deploy-production

build-api-gateway:
  extends: .build-backend-template

docker-api-gateway:
  extends: .docker-template
  needs:
    - job: build-api-gateway
      artifacts: true

deploy-staging-api-gateway:
  extends: .deploy-staging-template
  needs:
    - job: docker-api-gateway
      artifacts: true

deploy-production-api-gateway:
  extends: .deploy-production-template
  needs:
    - job: docker-api-gateway
      artifacts: true