include:
  - project: 'rouis.khawla09/gitlab-shared-template'
    ref: main
    file: '/pipeline.yml'

variables:
  SERVICE_NAME: books-service
  SERVICE_DIR: services/books-service
  SERVICE_TYPE: backend
  DOCKER_IMAGE: khawlarouiss/ci-cd-books

stages:
  - build
  - docker
  - deploy-staging
  - deploy-production

build-books-service:
  extends: .build-backend-template

docker-books-service:
  extends: .docker-template
  needs:
    - job: build-books-service
      artifacts: true

deploy-staging-books-service:
  extends: .deploy-staging-template
  needs:
    - job: docker-books-service
      artifacts: true

deploy-production-books-service:
  extends: .deploy-production-template
  needs:
    - job: docker-books-service
      artifacts: true