include:
  - project: 'rouis.khawla09/gitlab-shared-template'
    ref: main
    file: '/pipeline.yml'

variables:
  SERVICE_NAME: authors-service
  SERVICE_DIR: services/authors-service
  SERVICE_TYPE: backend
  DOCKER_IMAGE: khawlarouiss/ci-cd-authors

stages:
  - build
  - docker
  - deploy-staging
  - deploy-production

build-authors-service:
  extends: .build-backend-template

docker-authors-service:
  extends: .docker-template
  needs:
    - job: build-authors-service
      artifacts: true

deploy-staging-authors-service:
  extends: .deploy-staging-template
  needs:
    - job: docker-authors-service
      artifacts: true

deploy-production-authors-service:
  extends: .deploy-production-template
  needs:
    - job: docker-authors-service
      artifacts: true