include:
  - project: 'rouis.khawla09/gitlab-shared-template'
    ref: main
    file: '/pipeline.yml'

variables:
  SERVICE_TYPE: backend

stages:
  - test
  - build
  - docker
  - deploy-staging
  - deploy-production

test-authors-service:
  variables:
    SERVICE_DIR: services/authors-service
  extends: .test-backend-template

build-authors-service:
  variables:
    SERVICE_DIR: services/authors-service
  extends: .build-backend-template
  needs:
    - job: test-authors-service

docker-authors-service:
  variables:
    SERVICE_DIR: services/authors-service
    DOCKER_IMAGE: khawlarouiss/ci-cd-authors
  extends: .docker-template
  needs:
    - job: build-authors-service
      artifacts: true

deploy-staging-authors-service:
  variables:
    SERVICE_NAME: authors-service
  extends: .deploy-staging-template
  needs:
    - job: docker-authors-service
      artifacts: true

deploy-production-authors-service:
  variables:
    SERVICE_NAME: authors-service
  extends: .deploy-production-template
  needs:
    - job: docker-authors-service
      artifacts: true