include:
  - project: 'rouis.khawla09/gitlab-shared-template'
    ref: main
    file: '/pipeline.yml'

variables:
  SERVICE_TYPE: frontend

stages:
  - test
  - build
  - docker
  - deploy-staging
  - deploy-production

test-bookstore-frontend:
  variables:
    SERVICE_DIR: services/bookstore-frontend
  extends: .test-frontend-template

build-bookstore-frontend:
  variables:
    SERVICE_DIR: services/bookstore-frontend
  extends: .build-frontend-template
  needs:
    - job: test-bookstore-frontend

docker-bookstore-frontend:
  variables:
    SERVICE_DIR: services/bookstore-frontend
    DOCKER_IMAGE: khawlarouiss/ci-cd-bookstore-frontend
  extends: .docker-template
  needs:
    - job: build-bookstore-frontend
      artifacts: true

deploy-staging-bookstore-frontend:
  variables:
    SERVICE_NAME: bookstore-frontend
  extends: .deploy-staging-template
  needs:
    - job: docker-bookstore-frontend
      artifacts: true

deploy-production-bookstore-frontend:
  variables:
    SERVICE_NAME: bookstore-frontend
  extends: .deploy-production-template
  needs:
    - job: docker-bookstore-frontend
      artifacts: true