name: CI CD Pipeline Authors Service

on:
  push:
    branches: [main, dev]
    paths:
      - 'services/authors-service/**'

jobs:
  pipeline:
    uses: rouisskhawla/github-shared-workflow/.github/workflows/ci-cd-pipeline.yml@main
    with:
      service-name: authors
      docker-image: khawlarouiss/ci-cd-authors
      service-dir: services/authors-service
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}