name: CI CD Pipeline Books Service

on:
  push:
    branches: [main, dev]
    paths:
      - 'services/books-service/**'

jobs:
  pipeline:
    uses: rouisskhawla/github-shared-workflow/.github/workflows/ci-cd-pipeline.yml@main
    with:
      service-name: books-service
      docker-image: khawlarouiss/ci-cd-books
      service-dir: services/books-service
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      KUBECONFIG_DEV:  ${{ secrets.KUBECONFIG_DEV }}
      KUBECONFIG_PROD: ${{ secrets.KUBECONFIG_PROD }}